---
title: "Data in Motion, LLC: WeeK#19"
---

```{r}
url <- 'https://raw.githubusercontent.com/kedeisha1/Challenges/main/coaster_db.csv'
data<- read.csv(url)
```

```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(tidyr)

str(data)

#Question 1: How many columns and rows are in the dataset?
nrow(data)# number of rows 
ncol(data)# number of columns 
dim(data)
```


```{r}
#Question 2: Is there any missing data?

missing_data <- data %>% 
  summarise_all(~ sum(is.na(.))) %>% 
  pivot_longer(everything(), names_to = "Variable", values_to = "count_missing")

# Visualize and count missing data for each variable 
ggplot(missing_data, aes(x = count_missing, y = Variable, fill = Variable))+
  geom_col()
```


```{r}
#Question 3: Display the summary statistics of the numeric columns using the describe method.
library(psych)# describe function is from psych package

describe(data[, sapply(data, is.numeric)])# sapply used for numeric variabels 

```


```{r}
# Question 4:Rename the following columns:
# a. coaster_name ➡️ Coaster_Name
# b. year_introduced ➡️ Year_Introduced
# c. opening_date_clean ➡️ Opening_Date
# d. speed_mph ➡️ Speed_mph
# e. height_ft ➡️ Height_ft
# f. Inversions_clean ➡️ Inversions
# g. Gforce_clean ➡️ Gforce

data <- data %>% 
  rename(Coaster_Name = coaster_name, 
         Year_Introduced = year_introduced, 
         Opening_Date = opening_date_clean, 
         Speed_mph = speed_mph, 
         Height_ft = height_ft, 
         Inversion_status = Inversions_clean, # "Inversion" already existed in the dataframe, thus, it renamed as "Inversion_status"
         Gforce = Gforce_clean)
```


```{r}
# # Question 5: Are there any duplicated rows?

dup_rows <- data %>% 
  filter(duplicated(.))

nrow(dup_rows)# Zero duplicate rows 
```

```{r}
# # Question 6: What are the top 3 years with the most roller coasters introduced?
str(data)

top_three <- data %>% 
  group_by(Year_Introduced) %>% 
  count() 

ggplot(top_three, aes(x = Year_Introduced, y = n)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Year Introduced", y = "Number of Coasters") +
  ggtitle("Top Three Most Frequent Year of Introduction")+
  scale_x_continuous( breaks = unique(top_three$Year_Introduced))+ # to display year on x-axis 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) # to make "year" vertical on plot
 
```

*top three years* are 1998, 1999, 2000

```{r}

  
```

